import { Header } from "@/components/Header";
import { Hero } from "@/components/Home/Hero";
import { Showcase } from "@/components/Home/Showcase";
import { useI18n } from "@/hooks/useI18n";
import Head from "next/head";

export default function Home() {
  const dictionary = useI18n();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-main-black">
        <Header dictionary={dictionary.header} />
        <Hero dictionary={dictionary.home} />
        <Showcase />
      </main>
    </>
  );
}
